### ISSUE TITLE
Deprecations in Symfony 6.4

### ISSUE THREAD

**Issue by rmbl** [Pyrrah/GravatarBundle#12]
I'm currently testing an application with the beta and rc builds of Symfony 6.4. This bundle triggers a deprecation warning by extend from `Symfony\Component\Templating\Helper\Helper`:

`The "Pyrrah\GravatarBundle\Templating\Helper\GravatarHelper" class extends "Symfony\Component\Templating\Helper\Helper" that is deprecated since Symfony 6.4, use Twig instead.`

Extending from Helper seems unnecessary as no function of Helper is used in the bundle. Removing it would fix the deprecation warning.

**Comment by Pyrrah** [comment]
Hi @rmbl, thanks for your feedback!
Yes, you are right, this call to Helper is useless with SF4.4 to 6.4*. I removed it.
Have a nice day.

**Comment by rmbl** [comment]
Thank you for the fast response.

There will probably be a few more issues once I try to update to 7.0 though those changes might require a new major version of this bundle as it would increase the PHP version constraint. I will take a look at it once the first stable version is released.

**Comment by Pyrrah** [comment]
Thank you, I appreciate your suggestion to check the future version 7.0.

Any help is valuable on this project 🙂
Don't hesitate to come back if you notice others depreciations, or if you have any suggestions for the project.
